### ISSUE TITLE
Assertions failing (MaxTrackIndex < ACLBoneCount) crashing the editor (handling this more gracefully for content issues)

### ISSUE THREAD

**Issue by tomlooman** [nfrechette/acl-ue4-plugin#117] opened 2022-09-09 11:53 UTC
Asserts inside AnimBoneCompressionCodec_ACL.cpp crash the editor, we don't get much control to avoid this from trigger either. Once the default bone compression setting has been set via DefaultEngine.ini the system may compress an animation as soon as its shown in the content browser, causing this crash.

Exact error/line:
Assertion Failed: MaxTrackIndex < ACLBoneCount in AnimBoneCompressionCodec_ACL line 137 (using version 2.0.6)

Perhaps we can disable these checks more easily or use "ensure" instead of "check" if the failure is non critical and the editor should be allowed to continue execution.

**Comment by nfrechette** [comment] 2022-09-10 01:44
That is very strange. This check is there for a good reason, if we trip that assert, it means we are writing out of bounds because the buffer allocated just above is too small: `TrackToAtomsMap`.

The track indices come from this file: `...\Engine\Source\Runtime\Engine\Private\Animation\AnimCompressionTypes.cpp`
They are computed dynamically at runtime. UE builds a map of track index -> atom index. Atoms is what it calls joint transforms at runtime while tracks are the joint transforms in an anim sequence. The indices can differ for various reasons (e.g. retargetting).

The track indices for each anim sequence are stored after compression inside `CompressedTrackToSkeletonMapTable`. Under normal circumstances, this map and the compressed buffer should stay in sync and the max track count should remain consistent.

If the assert trips, it means that the compressed data has somehow gotten out of sync with that map. Normally, they are both computed from the same raw data.

Is this assert tripping 100% of the time for the same anim sequence? Can you take a look at what sort of track indices cause the assert to fail? Has the memory gotten corrupted somehow or do the values appear valid, just out of sync? Perhaps the editor async compression hits some weird thread contention issue but either way, I don't think ACL is causing that particular issue. Any corruption would have happened during compression.

You can also try launching with gflags enabled under Windows. That might shed some light if corruption is involved.

**Comment by tomlooman** [comment] 2022-09-10 08:10
The animation itself is out of sync, it's 100% repro and it appears that "TrackNames" has 178 entries while I expect only 164 when comparing it against other animations using the same skeleton. How that happened is unclear, the animation hasn't changed since using ACL as we just enabled it and I attempt to compress that animation.

The only bad thing about this situation is that it crashes the editor entirely, I would much rather have it notify me of the issue and move on, perhaps without compressing that animation or using a fallback compression.

**Comment by nfrechette** [comment] 2022-09-10 13:50
That's very strange. This assert is in the decompression code, by then the compression should be done and we cannot recover. I suspect that there is an edge case that ACL doesn't handle properly. The track names and skeleton joints can get out of sync, but how that happens isn't clear. Perhaps the animation was imported some time ago with a different skeleton. It is possible that re-importing the animation might fix this.

If possible, could you provide me with the anim sequence, skeleton, and a preview mesh to try and reproduce locally so that I can fix this? I'd be more than happy signing an NDA if required.

If not, I'll have to see if I can check for this some other way during compression to fail gracefully or figure out what might be going on so that I may handle it properly.

That part of the code hasn't really changed since the first release of the ACL plugin and you're the first to report this to me so I suspect it is quite uncommon.

**Comment by tomlooman** [comment] 2022-09-13 08:01
I'll look into getting you this animation, since it's the main character it may be difficult.

From my understanding, the animation was split (inside Unreal Engine?) from a larger animation sequence some time ago. This may have caused some invalid data to remain as it was modified.

Meanwhile, I'll see if there are any other animations that run into the same issue and whether a re-import fixes it. I've internally changed the assert checkf() to ensureMsgf() so I can continue execution while figuring out these animations.

**Comment by nfrechette** [comment] 2022-09-16 02:25
Sounds good, keep me posted. I'll look at this in the next week or two.
I've last heard of your issue about 5 years ago now but back then, it wasn't clear how it popped up, just that it could. Epic couldn't give me a clear answer and I wasn't able to reproduce this locally so I was never able to definitely handle this edge case.
I'll give it another shot and I'll keep you posted.

**Comment by nfrechette** [comment] 2022-09-25 01:59
@tomlooman I took a look at this and here is what I think is happening.
When ACL builds the compression data, we allocate one ACL track per bone, we look at the UE track index, and copy the data. If the UE skeleton has a bone with no UE track data, we tell ACL to strip it since it has no data. This is done [here](https://github.com/nfrechette/acl-ue4-plugin/blob/7a1b334113e88b90c938dae9c465ef8c6c945e58/ACLPlugin/Source/ACLPlugin/Private/ACLImpl.cpp#L131). The reasoning is that since at runtime we only used the compressed UE track indices, if it doesn't exist, we'll never query it.

This assumes that the skeleton bone list is a superset of the sequence track list. Extra bones are removed if they have no track data. But, perhaps some sequences (such as yours) have extra tracks with no corresponding bone. If that is the case, we might end up decompressing with a track index larger than the track count, tripping that important assert.

Can you confirm if this is the case with your anim sequence? Do you have tracks stripped in that line mentioned above? Do you have tracks in that sequence with no corresponding bone index? I'm 99% certain that the issue is related to one of these things.

I think a better way would be to have ACL allocate tracks based on the sequence track number, and avoid stripping altogether. If there are tracks with no corresponding bone in the skeleton, it'll be compressed but indices will match. That would likely be much safer and otherwise equivalent. Once I have a PR ready to fix this, I'll update this issue again and ping you.

**Comment by nfrechette** [comment] 2022-09-27 02:26
Hello @tomlooman, I have prepared a tentative fix in pull request #119 for the next patch release. The specific commit that should fix your issue is the following: https://github.com/nfrechette/acl-ue4-plugin/pull/119/commits/fc705ab38aee320a09843e5ce66ab70be3263039

I'd appreciate if you could give it a try to see if it resolves your problem. To validate that this was the issue, you can put a breakpoint in ACLImpl.cpp on line 200: `int32 ACLTrackIndex = NumBones;	// Start inserting at the end`
If we enter that branch, we had phantom raw tracks with no skeleton bones which might cause what you witnessed.

For the record, I am not in possession of any sequence with such phantom raw tracks and cannot confirm if this is indeed possible and/or your particular issue, hence why your help with this would be greatly appreciated :)

Note that the pull request above also includes a bunch of unrelated changes. Minor things and UE 5.1 and 5.2 support.

**Comment by nfrechette** [comment] 2022-11-03 01:58
Hello @tomlooman 
When you get the chance, I'd appreciate if you could give #119 a try. You can pull that branch and run the prepare_release.py script under Tools for your UE version.
I'm working to support 5.1 with the next release and I'm hoping to include a tentative fix for your issue. I would really appreciate if you could take it for a spin if you get the chance.

Cheers!

**Comment by nfrechette** [comment] 2023-01-21 01:50
Tentative fix has been included with 2.0.7. Let me know if it happens again!

**Closed as completed by nfrechette** 2023-01-21 01:50 UTC
Labels: bug
