### ISSUE TITLE
Crash in development build of UE4.26 when streaming in if insert many animation sequences into one database. 

### ISSUE THREAD

**Issue by NoahZuo** [nfrechette/acl-ue4-plugin#85] opened 2021-05-25 10:57 UTC
I am using 4.26 and have added many paragon character animation into my demo project. 

And I have set all anim sequences compressed with acl database(including additive animations) in one single database asset: 

![image](https://user-images.githubusercontent.com/10735147/119465881-acedfa80-bd76-11eb-9180-608fe8aa56c2.png)

When I change database visual fidelity from lowest to high in our development pack, it crashes like this: 

![image](https://user-images.githubusercontent.com/10735147/119464299-2ab10680-bd75-11eb-90dd-e2917ed09c82.png)

![image](https://user-images.githubusercontent.com/10735147/119466124-e9215b00-bd76-11eb-8f8d-730e31d86659.png)

This mostly happens if lowest tiers are not stripped and load from medium to high. 

**But it doesn't crash in editor**.

**Comment by nfrechette** [comment] 2021-05-26 01:53
Thank you for reporting this issue.

Unfortunately, after trying various things I was unable to reproduce this. I even ran with GFlags which should have caught any improper memory usage.

Could you provide a bit more context where the crash happens? Is the assert firing or do we have an invalid read/write on the next line? Which instruction is it crashing on?

How are you streaming in: through the console command or through blueprint? If the later, what does your blueprint look like?

Which platform does it crash on? I tested PC and Android without luck.

If this happens in a sample project, would it be possible for you to create a zip and share it with me? You can reach me in private at: zeno490@gmail.com

**Comment by NoahZuo** [comment] 2021-05-26 02:27
This is how I encounter this issue: 

1. Add Paragon character Phase to our project. 
2. Select all Phase animation, and set their bone compression setting to acl database. The database setting is like this: make sure you have `strip lowest importance tier` unchecked. 
3. In the level blueprint, call set visual fidelity to high when `F` is pressed. 
4. Cook content for windows. Running it in development mode through visual studio. 
5. Enter the scene, fine. And press `F`, boom! 

The crash is an invalid write: 
0xC0000005: Access violation writing location 0x0000012E0E8E4E65.

**Comment by NoahZuo** [comment] 2021-05-26 06:28
To provide more information. I've change the build configuration from Development to Debug. Still crash, but this time it is slightly different: 

![image](https://user-images.githubusercontent.com/10735147/119612582-a58a2800-be2e-11eb-8db6-ecf03f73bb49.png)

**Comment by NoahZuo** [comment] 2021-05-26 09:28
And here is what I am somehow confused. 

**When on earth is the function `UAnimationCompressionLibraryDatabase::BuildDatabase` get called? ** 

I am playing with the project I created yesterday now, and it never get called today... 

In the `PreSave` function, `ITargetPlatform` is always null, hence `BuildDatabase` never get called.

**Comment by NoahZuo** [comment] 2021-05-27 10:38
To provide more info. This is some watched variables when crash happens that we might have some interests: 

![image](https://user-images.githubusercontent.com/10735147/119811610-e3b04600-bf19-11eb-9b15-1ffb797466c7.png)

And this is the watched variables when streaming in medium tiers, this works fine and does not crash: 

![image](https://user-images.githubusercontent.com/10735147/119812366-ac8e6480-bf1a-11eb-9ddd-76c84e6894fe.png)

It seems that lower tier has 2 chunks to load. Can this have something to do with crash?

**Comment by nfrechette** [comment] 2021-05-28 02:26
Thank you for the detailed bug report!

Thanks to your insight about the multi chunk streaming, I was able to quickly narrow down the root cause.
The fix is in #87.

The core ACL regression test suite properly tests for multi chunk streaming but a bug slipped in the UE4 integration.
That should be taken care of now :)

I'd appreciate if you could try it out to validate that the fix works for you as well. I expect that I should be able to push the fix out into a new release as soon as I'm done validating everything.

>  When on earth is the function UAnimationCompressionLibraryDatabase::BuildDatabase get called?

That function is called from PreSave. During normal package saving to disk (e.g. from the editor when saving the asset), the target platform is null. During cooking, PreSave is call again with the proper target platform (e.g. PC, android, etc) and this is where hooks for platform specific things are and where cook only data is often generated when it isn't cached by the DDC. For example, UE4 implements animation frame stripping like this in UAnimSequence::PreSave if my memory serves me right.

ACL does the same and builds the database every time during cook on save. This is a fairly cheap operation that mostly moves memory around as all the heavy lifting has been done during compression. As you've noticed, the asset itself is small because the streamable data has to be stored in a separate bulk data file.

**Comment by NoahZuo** [comment] 2021-05-28 06:37
Good job! I've trid this fix, and it do works!

**Closed** 2021-05-31 01:31 UTC
Labels: bug
